### ISSUE TITLE
fix develop to support multiple languages

### ISSUE THREAD

**Issue by maxvisser** [teamforus/docs#51]
The issue is that the develop branch of this repository is 23 commits behind master while being a few commits ahead.

Therefore we can't merge master to develop. I think we should add all of the new content thats inside develop to seperate branches and delete it after. Then copy master and merge features back when finished.

**Comment by jamalv** [comment]
Agreed, so that means for now we could rename develop to develop_depreciated or something. And then create a new develop branch from master. When creating the new "feature" branches we can branch of develop, manually take the content from develop_depreciated, commit it to the new branch, finish it, and then merge to develop. Does that make sense?

**Comment by maxvisser** [comment]
i moved the content to a new branch called develop_depreciated and made a new develop branch that is even with master
